# Basic Information 
title: Yuanming (Alex) Tao
position: Incoming PhD student in applied maths
affiliation: The University of Sydney
affiliation_link: https://ymtao5219.github.io
affiliation_logo: ./assets/img/name-logo.svg
email: ytao5219 (at) gmail (dot) com

# Search Engine Optimization (SEO)
keywords: yuanming tao, taoyuanming, tao yuanming, alex tao
canonical: https://ymtao5219.github.io
description: Yuanming Tao is a PhD student at USYD. 

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: true

# Links
link_type: text #text/icon
google_scholar: https://scholar.google.com/citations?user=SCHOLAR_ID&user=dwIyWrEAAAAJ
cv_link: ./assets/pdf/yuanmingtao_resume.pdf
github_link: https://github.com/ymtao5219
linkedin: https://www.linkedin.com/in/yuanmingtao/
twitter: https://x.com/yuanmingta0

# Images 
avatar: ./assets/img/yuanmingtao_avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
footnote: This website is built with Hugo, utilizing the Minimal Light theme.
footnote_link: https://github.com/yaoyao-liu/minimal-light?tab=readme-ov-file

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: 

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
